spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: root
    #password: 123456
    url: jdbc:mysql://localhost:3306/collegestudentcall?characterEncoding=utf-8&useSSL=false&user=root&password=123456&serverTimezone=GMT&allowPublicKeyRetrieval=true
